name: tw_login
description:  modified  package for  personal usage. This pack  fixes 'TwitterKit/TwitterKit.h' file not found error. I am publishing this version for my own packages.  orginal package is on BSD 2-Clause "Simplified" License.
version: 1.1.1
repository: https://github.com/sabreys/flutter_twitter_login
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter




environment:
  sdk: ">=2.0.0 <3.0.0"