name: flutter_twitter_login
description:  modified  package for  personal usage. This pack  fixes 'TwitterKit/TwitterKit.h' file not found error.
version: 1.1.1
author: Iiro Krankka <iiro.krankka@gmail.com>
homepage: https://github.com/roughike/flutter_twitter_login

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.roughike.fluttertwitterlogin.fluttertwitterlogin
    pluginClass: TwitterLoginPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"